# Generated by Django 4.0.4 on 2022-05-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('ano', models.IntegerField(default=1)),
                ('semestre', models.IntegerField(default=1)),
                ('ects', models.IntegerField(default=6)),
                ('anoLetivoFrequentado', models.IntegerField(default=2020)),
                ('topicosAbordados', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('linkPagina', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64)),
                ('descricao', models.CharField(max_length=500)),
                ('imagem', models.ImageField(upload_to='')),
                ('anoRealizacao', models.IntegerField(default=2020)),
            ],
        ),
    ]
