# Generated by Django 4.0.4 on 2022-05-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='topicosAbordados',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
