# Generated by Django 4.0.4 on 2022-05-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_pessoa_linkpagina_cadeira_ranking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='linkCadeira',
            field=models.URLField(default=False),
        ),
    ]
