# Generated by Django 4.0.4 on 2022-05-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_cadeira_linkcadeira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='linkPaginaLinkedin',
            field=models.URLField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='linkPaginaLusofona',
            field=models.URLField(blank=True, default=False),
        ),
    ]
