# Generated by Django 4.0.4 on 2022-05-26 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_cadeira_semestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64)),
                ('descricao', models.CharField(max_length=512)),
                ('fotografia', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='cadeira',
            name='professores',
            field=models.ManyToManyField(to='portfolio.pessoa'),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='linkCadeira',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='semestre',
            field=models.IntegerField(choices=[(1, 'semestre 1'), (2, 'semestre 2'), (3, 'anual')], default=1),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='topicosAbordados',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='linkPaginaLinkedin',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='linkPaginaLusofona',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64)),
                ('descricao', models.CharField(max_length=512)),
                ('disciplinaAplicada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.cadeira')),
                ('projetos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.projeto')),
            ],
        ),
    ]
